name: Build and Push Docker Image (Multi-Platform)

on:
  push:
    branches:
      - main

permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - platform: linux/amd64
            tag_suffix: amd64
          - platform: linux/arm64
            tag_suffix: arm64
          - platform: linux/armv7
            tag_suffix: armv7

    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate tag with commit SHA
        id: prep
        run: echo ::set-output name=tag::$(echo ${GITHUB_REF#refs/heads/})-$(echo ${GITHUB_SHA} | head -c7)

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ghcr.io/hodladi/hodladiwallet/hodladiwallet:${{ steps.prep.outputs.tag }}-${{ matrix.tag_suffix }}
          platforms: ${{ matrix.platform }}
